### ISSUE TITLE
Einbinden von -chana- in Stata 14 / Encoding-Problem

### ISSUE THREAD

**Issue by UteH** [dzhw/data-supplements#1]
@anfranken Ich glaube, das ado bzw. das help-File ist nicht für Stata 14 codiert, zumindest sieht das help-File so aus?

Ist das prinzipiell ein Unterscheid von github und Stata oder kann man die Codierung des Files ändern o. ä.?

**Comment by anfranken** [comment]
Hab das Encoding auf utf8 gesetzt
