### ISSUE TITLE
Anleitung für ado-Installation

### ISSUE THREAD

**Issue by UteH** [dzhw/data-supplements#2]

**Comment by anfranken** [comment]
@UteH http://www.stata.com/support/faqs/programming/search-path-for-ado-files/ ???

**Comment by anfranken** [comment]
Hier nachzulesen: https://github.com/dzhw/data-supplements/blob/master/Ados/dzhw/fdz/INSTALLATION

**Comment by schellep** [comment]
du,

ich glaube nur die syntax-zeile

lab li `WLKmitString'

funktioniert nicht.

egal, bis mi. percy

Von: Andreas Franken [mailto:notifications@github.com]
Gesendet: Montag, 13. Februar 2017 16:52
An: dzhw/data-supplements
Cc: Subscribed
Betreff: Re: [dzhw/data-supplements] Anleitung für ado-Installation (#2)


Closed #2<https://github.com/dzhw/data-supplements/issues/2>.
